name: Craftus-Next

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_hash: ${{ steps.build.outputs.commit_hash }}

    steps:
      - uses: actions/checkout@v2

      - name: set up
        run: |
          sudo apt update
          sudo apt install g++ make gcc cmake
      - name: build
        id: build
        run: |
          #g++ nightlytool.cpp -o nightlytool
          mkdir -p ~/artifacts
          #cp nightlytool ~/artifacts
          echo ::set-output name=commit_tag::$(git describe --abbrev=0 --tags)
          echo ::set-output name=commit_hash::$(git log --format=%h -1)
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: ubuntu
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Build on Windows
        shell: bash
        run: |
          cd Platforms/Windows
          mkdir -p build
          cd build
          cmake ..
          cmake --build

      - name: "Publish build to GH Actions"
        uses: actions/upload-artifact@v2
        with:
          path: Craftus-Next.exe
          name: "windows"
